WORLD_WIDTH = 100
WORLD_HEIGHT = 100

DEFAULT_BATTERY_LEVEL = 100
DEFAULT_BATTERY_THRESHOLD = 20

DEFAULT_SPEED = 5
DEFAULT_CONSUMPTION = 1

DEFAULT_CHARGE_TIME = 10

DEFAULT_RIDER_COUNT = 5
DEFAULT_LOCKER_COUNT = 3

RIDER_STATUS_RIDING = "riding"
RIDER_STATUS_SEEKING = "seeking_locker"
RIDER_STATUS_STRANDED = "stranded"