DEFAULT_BATTERY_LEVEL = 100
DEFAULT_BATTERY_THRESHOLD = 20
DEFAULT_CONSUMPTION = 0.005

DEFAULT_CHARGE_TIME = 10

DEFAULT_RIDER_COUNT = 5
DEFAULT_LOCKER_COUNT = 3

MODE_DELIVERING = "delivering"
MODE_SEEKING_LOCKER = "seeking_locker"
MODE_ARRIVED = "arrived"
MODE_STRANDED = "stranded"
